### ISSUE TITLE
Please color code axis related stuff

### ISSUE THREAD

**Issue by RedramVS** [anegostudios/vsme#7]
Maybe this is premature, but in case it makes it easier to build in from the start, I'd just like to request that axis related items be color coded wherever possible.  For me personally, it's much easier and faster for me to associate colors than letters.   So when I'm looking at the model, I want the X Y and Z axis to be separate colors, and for those to correspond to any input fields.   I requested this feature from Tyron for vsmc, and it has been very nice.

**Comment by LunaTheFoxgirl** [comment]
This has been implemented in https://github.com/anegostudios/vsme/commit/63952b7cc6a1fde6bd1a238aad81fe7093da49e8
